version: '3'
services:
  dbpostgres:
    image: 'postgres:12-alpine'
    container_name: 'teamspeak_bot_db'
    ports:
      - '5430:5432'
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
